export { default as Login } from './Login';
// export { default as Home } from './Home';
export { default as SidePanel } from './SidePanel';
export { default as WelComePage } from './WelComePage';
export { default as Layout } from './Layout';
export { default as ToggleLanguage } from './ToggleLanguage';
export { default as Projects } from './Projects';
export { default as Project } from './Issues';
export { default as ProjectCreation } from './ProjectCreation';
export { default as Account } from './Account';
export { default as Previlige } from './Previlige';
export { default as Page403 } from './Page403';
export { default as ResetPassword } from './ResetPassword';
export { default as IssueDetail } from './IssueDetail';
