export const MONITOR_LOGIN_BEGIN = 'MONITOR_LOGIN_BEGIN';
export const MONITOR_LOGIN_SUCCESS = 'MONITOR_LOGIN_SUCCESS';
export const MONITOR_LOGIN_FAILURE = 'MONITOR_LOGIN_FAILURE';
export const MONITOR_LOGIN_DISMISS_ERROR = 'MONITOR_LOGIN_DISMISS_ERROR';
export const MONITOR_LANGUAGE_SET_ZH = 'MONITOR_LANGUAGE_SET_ZH';
export const MONITOR_LANGUAGE_SET_EN = 'MONITOR_LANGUAGE_SET_EN';
